name: reversi_game
description: "Reversi chess"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  flutter_bloc: ^9.1.0
  socket_io_client: ^3.1.1
  freezed_annotation: ^3.0.0
  freezed: ^3.0.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/black_piece.png
    - assets/white_piece.png
